### ISSUE TITLE
Incorrect way of assigning bash variable

### ISSUE THREAD

**Issue by laggykiller** [st-ty1/Arch-Linux_firmware-mod-kit#1]
For install_patched_fmk.sh
`$FMK_DIR=$HOME/firmware-mod-kit`
`$FMK_PATH_DIR=$HOME/Documents/firmware-mod-kit`

Should be changed to
`FMK_DIR=$HOME/firmware-mod-kit`
`FMK_PATH_DIR=$HOME/Documents/firmware-mod-kit`

**Comment by st-ty1** [comment]
edited. Thanks.
